"""PostgreSQL persistence contracts and repositories."""

from note_rag.persistence.database import Database
from note_rag.persistence.models import (
    Base,
    CacheState,
    ChatMessageRecord,
    ChatRole,
    ChunkRecord,
    Conversation,
    Course,
    CourseDocument,
    Document,
    DocumentStatus,
    IndexingStatus,
    IngestionJob,
    IngestionJobStatus,
    QueryEmbeddingCache,
    RetrievalResultCache,
    Topic,
    TopicSource,
    TopicState,
)
from note_rag.persistence.repositories import (
    ChatMessageRepository,
    ChunkRepository,
    ConversationRepository,
    CourseRepository,
    DocumentRepository,
    IngestionJobRepository,
    TopicRepository,
)

__all__ = [
    "Base",
    "CacheState",
    "ChatMessageRecord",
    "ChatMessageRepository",
    "ChatRole",
    "ChunkRecord",
    "ChunkRepository",
    "Conversation",
    "ConversationRepository",
    "Course",
    "CourseDocument",
    "CourseRepository",
    "Database",
    "Document",
    "DocumentRepository",
    "DocumentStatus",
    "IngestionJob",
    "IngestionJobRepository",
    "IngestionJobStatus",
    "IndexingStatus",
    "QueryEmbeddingCache",
    "RetrievalResultCache",
    "Topic",
    "TopicRepository",
    "TopicSource",
    "TopicState",
]
